package Tema4.Medico;

public enum Especialidad {
    /**
     * GENERAL,DIGESTIVO, OTORRINO, CARDIOLOGIA, NEUROLOGIA, TRAUMATOLOGIA
     */

    GENERAL,
    DIGESTIVO,
    OTORRINO,
    CARDIOLOGIA,
    NEUROLOGIA,
    TRAUMATOLOGIA

}
